### ISSUE TITLE
`len` always returns 20

### ISSUE THREAD

**Issue by blasrodri** [mental32/monty#10]
Expected behaviour:
```py
assert(len([1, 2, 3]) == 3)
```
Current behaviour:
```py
assert(len([1, 2, 3]) == 20)
```

**Comment by mental32** [comment]
* assert is not compilable
* lists literals are not compilable nor able to be represented in the type system
* len is definitely UB

How exactly did you get the current behavior to work??

**Comment by blasrodri** [comment]
Thanks @mental32 
What do you mean by 
> len is UB
I don't remember how I got this to run, actually.
