### ISSUE TITLE
Just a few ideas on various narrowing ways

### ISSUE THREAD

**Issue by aldanor** [mental32/monty#25]
You've probably already considered this, just tried to think of commonly used ways to branch on type :)

```python
# same narrowing
if isinstance(x, int): ...
if type(x) is int: ...
if issubclass(type(x), int): ...
```

Special cases with singleton stuff, obviously, like:

```python
# same narrowing
if x is None: ...  # (!)
if type(x) is type(None): ...
if isinstance(x, type(None)): ...
if issubclass(type(x), type(None)): ...
```

More obscure narrowing cases, but should follow automatically if everything's done properly:

```python
# say y is an int
if isinstance(x, type(y)): ...
if type(x) is type(y): ...
if issubclass(type(x), type(y)): ...
```

**Comment by aldanor** [comment]
A few more - if type is stored in a variable:

```
tp = type(x)
if tp is int: ...
if issubclass(tp, int): ...
```

**Comment by mental32** [comment]
So I think this can be boiled down to three main patterns:

* `X is Y`
* `isinstance(X, Y)`
* `issubclass(X, Y)`

where X and Y maybe expressions that are const evaluable and resolve into class/type instances.
All three are certainly possible and probably good to have.

Right now it's real easy to limit this to only work when the test of a branch contains exactly one of the three patterns but in an ideal world it would work in larger arbitrarily complex logic circuits i.e. `x is not None and (isinstance(x, Y) or isinstance(x, Z))` where `x` is inferred to be `Union[Y, Z]` within the body of the branch. I'll need to figure out how to get that done somehow, but covering the explicit simple case is easy.

**Comment by aldanor** [comment]
Yep. Note that booleans also fall under the singleton category, although, e.g. `if x is True` or `if x == True`.

Btw `if x == None` should also be under the singleton case. Technically, for singletons you can also compare `id(x)` but that's really an edge case...

Next thing, obviously, is all sort of logical expressions as you pointed out above.

And then there's more complicated expressions, e.g. containing `in` and equality ops. Not sure you want to support something like the example below, but it works in CPython because it's valid to compare strings to ints to lists (and more generally, the common rule in Python is to allow equality comparison of everything, just return false):

```python
x: str | int | list[int]

if isinstance(x, str) or x in (2, 3):
    # here x is str | int
if x in ('a', 'b'):
    # here x is str
```

This might be looking too far ahead at this point, but might be nice to have some examples outlined :)

**Comment by mental32** [comment]
I don't think for the moment it makes sense to treat `==` specially, perhaps in the future it'll be worth considering.

The `x in tuple` is interesting and I have not thought about it yet. On one side I want this to work but on the other hand it'll have to involve some intrinsic magic since `in` would invoke either `__contains__` or the other membership dunders but for the tuple case I think it'd be nice to have some sort of desugaring process that allows that.

**Comment by mental32** [comment]
Dropping this link here: https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards

It talks about what type guarding and narrowing operations are allowed in Pyrite and I feel like it will be a good resource.
